### ISSUE TITLE
Web: Functionality. Display items. (0.5 days)

### ISSUE THREAD

**Issue by KirillKudaev** [KirillKudaev/PrinCraigslist#3]
As a user, I want a way to see a list of all available items for sale as well as display a specific item in more detail.

Create a page with the necessary elements to communicate with the parse server to display a list of items for sale in the database.
Create the necessary back-end structure to enable such querying.

**Comment by ggoodsell694** [comment]
**For All Items** - any combination of the
Get   /   Get categoryId = {categoryId} / Get title = {substring of title}    
Return, for each Item matching the search criteria from database: the item id, user id, title, description, picture, category id, postedDate and price. These items will be returned as a list of json objects.

**For A Specific Item**
Get id={itemId}
Return the specific item with the matching itemId from database: the item id, user id, title, description, picture, category id, postedDate and price. The item will be returned as a json object.
