### ISSUE TITLE
Web: Functionality. Create an item for sale. (0.5 days)

### ISSUE THREAD

**Issue by KirillKudaev** [KirillKudaev/PrinCraigslist#4]
As a user, I want a way to post an item I would like to sell. 

Each item should have the following information: userId (to identify the user who posted the items), title, description, picture, categoryId, price, and postedDate. Some requirements on those fields are: the title cannot exceed 80 characters, the picture must be a jpeg format, price must be a decimal number. postedDate will be created automatically when the user posts the item. The allowed categories are: Books, Bikes, Electronics, Clothing, Jobs, and Other and the translation of the category to the categoryId will take place on the front end. The userId field will be automatically added to the post from the session information of the current user.

If a post does not contain the userId, title, categoryId, price, or postedDate return an error.

**Comment by ggoodsell694** [comment]
Each item should have the following information: userName (to identify the user who posted the items), title, description, picture, category, price, and postedDate. Some requirements on those fields are: the userName cannot exceed 20 characters, the title cannot exceed 80 characters, the picture must be a jpeg format, price must be a decimal number. postedDate will be created automatically when the user posts the item. The allowed categories are: Books, Bikes, Electronics, Clothing, Jobs, and Other. The userName field will be automatically added to the post from the session information of the current user. 

If a post does not contain the userName, title, category, price, or postedDate return an error.
