### ISSUE TITLE
Web: Functionality. Update an existing item. (0.5 days)

### ISSUE THREAD

**Issue by KirillKudaev** [KirillKudaev/PrinCraigslist#5]
As a user, I want a way to update my items for sale.

**Comment by ggoodsell694** [comment]
Each put request should only update one or more of the following fields: title, description, picture, category, and price. If any additional fields are included, throw an error. The same restrictions apply to the put request as the post:  the title cannot exceed 80 characters, description cannot exceed 1,000 characters, the picture must be a jpeg format, price must be a decimal number. The allowed categories are: Books, Bikes, Electronics, Clothing, Jobs, and Other. 

postedDate and userName will not change as a result of a put request.
